
version: '3.8'
services:
  snippng-next:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
